# Generated by Django 4.0 on 2022-01-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('degree_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=120)),
                ('freelancer', models.CharField(max_length=20)),
                ('Description_top', models.TextField()),
                ('Description_bottom', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=300)),
                ('details', models.TextField()),
                ('university_name', models.CharField(max_length=100)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Happy_Clients', models.IntegerField()),
                ('Projects', models.IntegerField()),
                ('Hours_Of_Support', models.IntegerField()),
                ('Hard_Workers', models.IntegerField()),
                ('Facts_descprition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=80)),
                ('Client', models.CharField(max_length=50)),
                ('Project_date', models.DateTimeField()),
                ('Project_Details', models.TextField()),
                ('Project_URL', models.CharField(max_length=80)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'ordering': ('-Project_date',),
            },
        ),
        migrations.CreateModel(
            name='Portfolio_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professional_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=40)),
                ('details_list1', models.TextField()),
                ('details_list2', models.TextField()),
                ('details_list3', models.TextField()),
                ('details_list4', models.TextField()),
                ('details_list5', models.TextField()),
                ('city', models.CharField(max_length=40)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_offered', models.CharField(max_length=30)),
                ('service_detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillS_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('address', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('client_testimony', models.TextField()),
                ('client_occupation', models.CharField(max_length=30)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
