# Generated by Django 4.0 on 2022-01-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('message', models.TextField(verbose_name='Message')),
                ('subject', models.TextField(verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'ContactProfile',
                'verbose_name_plural': 'ContactProfileS',
                'ordering': ['timestamp'],
            },
        ),
    ]
